version: '3.9'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./start-flask
    volumes:
      - './api:/usr/src/app'
    ports:
      - ${FLASK_APP_PORT}:5000
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy
      vsftpd:
        condition: service_started
      redis:
        condition: service_started

  celery_worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./start-celeryworker
    volumes:
      - './api:/usr/src/app'
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy
      api:
        condition: service_started
      vsftpd:
        condition: service_started
      redis:
        condition: service_started

  celery_beat:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./start-celerybeat
    volumes:
      - './api:/usr/src/app'
    env_file:
      - .env
    environment:
      - FLASK_APP=project
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      mysqldb:
        condition: service_healthy
      api:
        condition: service_started
      celery_worker:
        condition: service_started
      vsftpd:
        condition: service_started
      redis:
        condition: service_started

  flower:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./start-flower
    volumes:
      - './api:/usr/src/app'
    env_file:
      - .env
    ports:
      - ${FLOWER_PORT}:5555
    depends_on:
      - api
      - celery_worker
      - celery_beat
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:8080
    depends_on:
      - api
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3008:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:${NGINX_PORT}
    depends_on:
      - api

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
      ADMINER_DESIGN: galkaev
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      mysqldb:
        condition: service_started

  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - my-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASS}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  vsftpd:
    image: fauria/vsftpd:latest
    restart: always
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - PASV_ADDRESS=vsftpd
      - PASV_ADDR_RESOLVE=YES
      - LOG_STDOUT=YES
    ports:
      - "${FTP_PORT}:21"
    volumes:
      - ./ftp:/home/vsftpd

  redis:
    image: redis:6-alpine

volumes:
  my-data:
