"""empty message

Revision ID: 1d3e3dc30152
Revises: 442bdf93d028
Create Date: 2022-04-28 22:58:48.487749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3e3dc30152'
down_revision = '442bdf93d028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('in_custody', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'in_custody')
    # ### end Alembic commands ###
